# Generated by Django 5.2.6 on 2025-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image')),
                ('rating', models.FloatField()),
                ('price', models.FloatField()),
                ('categories', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
