# Generated by Django 4.2 on 2025-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
