# Generated by Django 5.2.7 on 2025-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_product_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.TextField(),
        ),
    ]
